# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting

# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
# env = AQ_DRM_DEVICES,/dev/dri/card1
# https://chatgpt.com/c/6a088d1b-724c-83e8-a0bc-fd5cebf47ee2
# env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0:/dev/dri/card3

# env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0:/dev/dri/card3
# env = WLR_DRM_NO_ATOMIC,1
# env = AQ_FORCE_LINEAR_BLIT,0
env = WLR_NO_HARDWARE_CURSORS,1

xwayland {
  force_zero_scaling = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
